from __future__ import annotations

from dataclasses import dataclass

from app.utils import slugify


@dataclass(slots=True)
class ScaffoldSpec:
    project_name: str
    service_name: str
    stack: str
    project_slug: str
    acceptance_criteria: list[str]
    key_capabilities: list[str]


class ProjectWriter:
    def build(self, spec: ScaffoldSpec) -> dict[str, str]:
        if spec.stack == "go-gin":
            return self._build_go(spec)
        if spec.stack == "spring-boot":
            return self._build_spring(spec)
        return self._build_fastapi(spec)

    def _build_fastapi(self, spec: ScaffoldSpec) -> dict[str, str]:
        criteria_lines = "\n".join(f"- {item}" for item in spec.acceptance_criteria)
        return {
            f"scaffold/{spec.project_slug}/README.md": f"""# {spec.project_name} Starter

Generated by MimoForge for the `{spec.stack}` stack.

## Acceptance Criteria
{criteria_lines}

## Run
```bash
pip install -r requirements.txt
uvicorn app.main:app --reload
```
""",
            f"scaffold/{spec.project_slug}/requirements.txt": "fastapi==0.115.0\nuvicorn==0.30.6\n",
            f"scaffold/{spec.project_slug}/app/main.py": f"""from fastapi import FastAPI

app = FastAPI(title="{spec.project_name}")


@app.get("/healthz")
async def healthz() -> dict[str, str]:
    return {{"status": "ok", "service": "{spec.service_name}"}}


@app.get("/capabilities")
async def capabilities() -> dict[str, list[str]]:
    return {{"items": {spec.key_capabilities!r}}}
""",
            f"scaffold/{spec.project_slug}/tests/test_health.py": """from app.main import app
from fastapi.testclient import TestClient


def test_healthz() -> None:
    client = TestClient(app)
    response = client.get("/healthz")
    assert response.status_code == 200
    assert response.json()["status"] == "ok"
""",
            f"scaffold/{spec.project_slug}/Dockerfile": """FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app ./app
CMD ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
""",
            f"scaffold/{spec.project_slug}/deploy/k8s/deployment.yaml": f"""apiVersion: apps/v1
kind: Deployment
metadata:
  name: {spec.service_name}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {spec.service_name}
  template:
    metadata:
      labels:
        app: {spec.service_name}
    spec:
      containers:
        - name: api
          image: ghcr.io/your-org/{spec.service_name}:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
""",
            f"scaffold/{spec.project_slug}/deploy/k8s/service.yaml": f"""apiVersion: v1
kind: Service
metadata:
  name: {spec.service_name}
spec:
  selector:
    app: {spec.service_name}
  ports:
    - port: 80
      targetPort: 8080
""",
        }

    def _build_go(self, spec: ScaffoldSpec) -> dict[str, str]:
        module_name = slugify(spec.project_name).replace("-", "")
        return {
            f"scaffold/{spec.project_slug}/README.md": f"# {spec.project_name} Go Starter\n\nGenerated by MimoForge.\n",
            f"scaffold/{spec.project_slug}/go.mod": f"module github.com/your-org/{module_name}\n\ngo 1.22\n\nrequire github.com/gin-gonic/gin v1.10.0\n",
            f"scaffold/{spec.project_slug}/cmd/api/main.go": f"""package main

import "github.com/gin-gonic/gin"

func main() {{
    router := gin.Default()
    router.GET("/healthz", func(ctx *gin.Context) {{
        ctx.JSON(200, gin.H{{"status": "ok", "service": "{spec.service_name}"}})
    }})
    router.Run(":8080")
}}
""",
            f"scaffold/{spec.project_slug}/Dockerfile": """FROM golang:1.22-alpine AS builder
WORKDIR /src
COPY . .
RUN go build -o api ./cmd/api

FROM alpine:3.20
WORKDIR /app
COPY --from=builder /src/api ./api
CMD ["./api"]
""",
            f"scaffold/{spec.project_slug}/deploy/k8s/deployment.yaml": f"""apiVersion: apps/v1
kind: Deployment
metadata:
  name: {spec.service_name}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {spec.service_name}
  template:
    metadata:
      labels:
        app: {spec.service_name}
    spec:
      containers:
        - name: api
          image: ghcr.io/your-org/{spec.service_name}:latest
          ports:
            - containerPort: 8080
""",
        }

    def _build_spring(self, spec: ScaffoldSpec) -> dict[str, str]:
        package_path = "com/example/mimoforge"
        java_package = package_path.replace("/", ".")
        return {
            f"scaffold/{spec.project_slug}/README.md": f"# {spec.project_name} Spring Starter\n\nGenerated by MimoForge.\n",
            f"scaffold/{spec.project_slug}/pom.xml": """<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>mimoforge-service</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.3.2</version>
  </parent>
  <properties>
    <java.version>21</java.version>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
""",
            f"scaffold/{spec.project_slug}/src/main/java/{package_path}/DemoApplication.java": f"""package {java_package};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class DemoApplication {{
    public static void main(String[] args) {{
        SpringApplication.run(DemoApplication.class, args);
    }}
}}
""",
            f"scaffold/{spec.project_slug}/src/main/java/{package_path}/HealthController.java": f"""package {java_package};

import java.util.Map;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class HealthController {{
    @GetMapping("/healthz")
    public Map<String, String> healthz() {{
        return Map.of("status", "ok", "service", "{spec.service_name}");
    }}
}}
""",
            f"scaffold/{spec.project_slug}/Dockerfile": """FROM maven:3.9-eclipse-temurin-21 AS builder
WORKDIR /workspace
COPY . .
RUN mvn -q -DskipTests package

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=builder /workspace/target/*.jar app.jar
CMD ["java", "-jar", "app.jar"]
""",
        }

